Repository OCA/stock-weighing, pull requests merged in 2024-09, with the labels that each got.

#1 [15.0][ADD] stock_weighing: New module
  setup/stock_weighing/odoo/addons/stock_weighing
  setup/stock_weighing/setup.py
  stock_weighing/README.rst
  stock_weighing/__init__.py
  stock_weighing/__manifest__.py
  stock_weighing/controllers/__init__.py
  stock_weighing/controllers/start_screen.py
  stock_weighing/demo/picking_type_demo.xml
  stock_weighing/demo/weight_label_demo.xml
  stock_weighing/i18n/es.po
  stock_weighing/i18n/stock_weighing.pot
  stock_weighing/init_hook.py
  stock_weighing/models/__init__.py
  stock_weighing/models/stock_move.py
  stock_weighing/models/stock_move_line.py
  stock_weighing/models/stock_picking.py
  stock_weighing/models/stock_picking_type.py
  stock_weighing/models/weighing_mixin.py
  stock_weighing/readme/CONFIGURE.md
  stock_weighing/readme/CONTEXT.md
  stock_weighing/readme/CONTRIBUTORS.md
  stock_weighing/readme/DESCRIPTION.md
  stock_weighing/readme/ROADMAP.md
  stock_weighing/readme/USAGE.md
  stock_weighing/security/ir.model.access.csv
  stock_weighing/static/description/icon.png
  stock_weighing/static/description/icon.svg
  stock_weighing/static/description/index.html
  stock_weighing/static/src/base_weight_record_form/base_weight_record_form.esm.js
  stock_weighing/static/src/base_weight_record_form/base_weight_record_form.xml
  stock_weighing/static/src/base_weight_record_kanban/base_weight_record_kanban.esm.js
  stock_weighing/static/src/base_weight_record_kanban/base_weight_record_kanban.scss
  stock_weighing/static/src/base_weight_record_kanban/base_weight_record_kanban.xml
  stock_weighing/views/start_screen_banner.xml
  stock_weighing/views/stock_move_line_views.xml
  stock_weighing/views/stock_move_views.xml
  stock_weighing/views/stock_picking_type_views.xml
  stock_weighing/views/stock_picking_views.xml
  stock_weighing/wizards/__init__.py
  stock_weighing/wizards/weigh_operation_selection.py
  stock_weighing/wizards/weigh_operation_selection_views.xml
  stock_weighing/wizards/weighing_wizard.py
  stock_weighing/wizards/weighing_wizard_views.xml
Labels: approved, bot is merging ⏳

#15 [15.0][FIX] stock_weighing: Stock move operations button is shown when all detailed operations already displayed
  stock_weighing/models/stock_move.py
Labels: approved, bot is merging ⏳

#16 [15.0][IMP] stock_weighing: Reload weighing wizard to allow add multiple weighing
  stock_weighing/models/stock_move_line.py
  stock_weighing/wizards/weighing_wizard.py
  stock_weighing/wizards/weighing_wizard_views.xml
Labels: approved, bot is merging ⏳

#9 [15.0][ADD] partner_delivery_zone_weighing: New module
  partner_delivery_zone_weighing/README.rst
  partner_delivery_zone_weighing/__init__.py
  partner_delivery_zone_weighing/__manifest__.py
  partner_delivery_zone_weighing/readme/CONTRIBUTORS.md
  partner_delivery_zone_weighing/readme/DESCRIPTION.md
  partner_delivery_zone_weighing/static/description/index.html
  partner_delivery_zone_weighing/views/stock_move_views.xml
  setup/partner_delivery_zone_weighing/odoo/addons/partner_delivery_zone_weighing
  setup/partner_delivery_zone_weighing/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#5 [15.0][ADD] stock_secondary_unit_weighing: New module
  setup/stock_secondary_unit_weighing/odoo/addons/stock_secondary_unit_weighing
  setup/stock_secondary_unit_weighing/setup.py
  stock_secondary_unit_weighing/README.rst
  stock_secondary_unit_weighing/__init__.py
  stock_secondary_unit_weighing/__manifest__.py
  stock_secondary_unit_weighing/i18n/es.po
  stock_secondary_unit_weighing/i18n/stock_secondary_unit_weighing.pot
  stock_secondary_unit_weighing/models/__init__.py
  stock_secondary_unit_weighing/models/stock_move.py
  stock_secondary_unit_weighing/models/stock_move_line.py
  stock_secondary_unit_weighing/readme/CONTRIBUTORS.md
  stock_secondary_unit_weighing/readme/DESCRIPTION.md
  stock_secondary_unit_weighing/static/description/index.html
  stock_secondary_unit_weighing/views/stock_move_views.xml
Labels: bot is merging ⏳

#7 [15.0][ADD] stock_weighing_remote_measure: New module
  setup/stock_weighing_remote_measure/odoo/addons/stock_weighing_remote_measure
  setup/stock_weighing_remote_measure/setup.py
  stock_weighing_remote_measure/README.rst
  stock_weighing_remote_measure/__init__.py
  stock_weighing_remote_measure/__manifest__.py
  stock_weighing_remote_measure/i18n/es.po
  stock_weighing_remote_measure/i18n/stock_weighing_remote_measure.pot
  stock_weighing_remote_measure/readme/DESCRIPTION.md
  stock_weighing_remote_measure/readme/README.md
  stock_weighing_remote_measure/static/description/index.html
  stock_weighing_remote_measure/static/src/js/weight_record_form_widget.esm.js
  stock_weighing_remote_measure/static/src/scss/weight_wizard.scss
  stock_weighing_remote_measure/static/src/xml/weight_record_form_widget.xml
  stock_weighing_remote_measure/wizards/__init__.py
  stock_weighing_remote_measure/wizards/weighing_wizard.py
  stock_weighing_remote_measure/wizards/weighing_wizard_views.xml
Labels: approved, bot is merging ⏳

#4 [15.0][ADD] stock_picking_batch_weighing: New module
  setup/stock_picking_batch_weighing/odoo/addons/stock_picking_batch_weighing
  setup/stock_picking_batch_weighing/setup.py
  stock_picking_batch_weighing/README.rst
  stock_picking_batch_weighing/__init__.py
  stock_picking_batch_weighing/__manifest__.py
  stock_picking_batch_weighing/i18n/es.po
  stock_picking_batch_weighing/i18n/stock_picking_batch_weighing.pot
  stock_picking_batch_weighing/models/__init__.py
  stock_picking_batch_weighing/models/stock_move.py
  stock_picking_batch_weighing/models/stock_picking_batch.py
  stock_picking_batch_weighing/readme/CONTRIBUTORS.md
  stock_picking_batch_weighing/readme/DESCRIPTION.md
  stock_picking_batch_weighing/static/description/index.html
  stock_picking_batch_weighing/views/stock_picking_batch_views.xml
  stock_picking_batch_weighing/wizards/__init__.py
  stock_picking_batch_weighing/wizards/weigh_operation_selection.py
Labels: approved, bot is merging ⏳, ready to merge

#2 [15.0][ADD] sale_stock_weighing: New module
  sale_stock_weighing/README.rst
  sale_stock_weighing/__init__.py
  sale_stock_weighing/__manifest__.py
  sale_stock_weighing/models/__init__.py
  sale_stock_weighing/models/stock_move.py
  sale_stock_weighing/readme/CONTRIBUTORS.md
  sale_stock_weighing/readme/DESCRIPTION.md
  sale_stock_weighing/static/description/index.html
  sale_stock_weighing/views/stock_move_views.xml
  setup/sale_stock_weighing/odoo/addons/sale_stock_weighing
  setup/sale_stock_weighing/setup.py
Labels: approved, bot is merging ⏳, stale, ready to merge

#3 [15.0][ADD] sale_elaboration_weighing: New module
  sale_elaboration_weighing/README.rst
  sale_elaboration_weighing/__init__.py
  sale_elaboration_weighing/__manifest__.py
  sale_elaboration_weighing/i18n/es.po
  sale_elaboration_weighing/i18n/sale_elaboration_weighing.pot
  sale_elaboration_weighing/models/__init__.py
  sale_elaboration_weighing/models/stock_move.py
  sale_elaboration_weighing/readme/CONTRIBUTORS.md
  sale_elaboration_weighing/readme/DESCRIPTION.md
  sale_elaboration_weighing/static/description/index.html
  sale_elaboration_weighing/static/src/scss/stock_weighing.scss
  sale_elaboration_weighing/views/stock_move_views.xml
  sale_elaboration_weighing/wizards/__init__.py
  sale_elaboration_weighing/wizards/weigh_operation_selection.py
  setup/sale_elaboration_weighing/odoo/addons/sale_elaboration_weighing
  setup/sale_elaboration_weighing/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#6 [15.0][ADD] stock_weighing_auto_create_lot: New module
  setup/stock_weighing_auto_create_lot/odoo/addons/stock_weighing_auto_create_lot
  setup/stock_weighing_auto_create_lot/setup.py
  stock_weighing_auto_create_lot/README.rst
  stock_weighing_auto_create_lot/__init__.py
  stock_weighing_auto_create_lot/__manifest__.py
  stock_weighing_auto_create_lot/i18n/es.po
  stock_weighing_auto_create_lot/i18n/stock_weighing_auto_create_lot.pot
  stock_weighing_auto_create_lot/readme/CONFIGURE.md
  stock_weighing_auto_create_lot/readme/CONTRIBUTORS.md
  stock_weighing_auto_create_lot/readme/DESCRIPTION.md
  stock_weighing_auto_create_lot/static/description/index.html
  stock_weighing_auto_create_lot/wizards/__init__.py
  stock_weighing_auto_create_lot/wizards/weighing_wizard.py
  stock_weighing_auto_create_lot/wizards/weighing_wizard_views.xml
Labels: approved, bot is merging ⏳

#8 [15.0][ADD] stock_weighing_threaded_print: New module
  setup/stock_weighing_threaded_print/odoo/addons/stock_weighing_threaded_print
  setup/stock_weighing_threaded_print/setup.py
  stock_weighing_threaded_print/README.rst
  stock_weighing_threaded_print/__init__.py
  stock_weighing_threaded_print/__manifest__.py
  stock_weighing_threaded_print/models/__init__.py
  stock_weighing_threaded_print/models/stock_move_line.py
  stock_weighing_threaded_print/readme/CONFIGURE.rst
  stock_weighing_threaded_print/readme/CONTRIBUTORS.rst
  stock_weighing_threaded_print/readme/DESCRIPTION.rst
  stock_weighing_threaded_print/static/description/icon.png
  stock_weighing_threaded_print/static/description/index.html
  stock_weighing_threaded_print/wizards/__init__.py
  stock_weighing_threaded_print/wizards/weighing_wizard.py
Labels: approved, bot is merging ⏳, no stale
